### ISSUE TITLE
yelp_clog silently fails for all future logs if called once before being configured

### ISSUE THREAD

**Issue by jwien001** [Yelp/yelp_clog#32]
If `log_line` is called before logging is configured, `check_create_default_loggers` will not add any loggers to the global list, but will change it's value from `None`. Then, every subsequent time `log_line` is called, we'll skip adding loggers because the global variable is no longer `None`, but won't log anything because there are no loggers. This produces no errors and is very difficult to identify and track down when it occurs.

eliot@ proposed a rough solution seen here: https://i.fluffy.cc/zqpqGxDBv8Rd5Mb99b2p9xZg83fCSt8J.html. Something along these lines would make an early call to `log_line` fail loudly and prevent us from getting into a silently failing logging situation in the future.

**Comment by ketanyelp** [comment]
Instead of failing loudly, I've opened a pull request that makes the loggers get reinitialized if they are empty. This way, if clog.log_line is called to early and loggers is set to empty list, the next call can fix it up and set it to the correct values based on the configs.

#https://github.com/Yelp/yelp_clog/pull/33/

**Comment by asottile** [comment]
I actually think failing loudly is a better option since it helps fix the
code instead of silently doing nothing

**Comment by ketanyelp** [comment]
That makes sense, but I want to log stuff from a DB Model. The problem was that log_line() was called from that DB Model when batch jobs imported it (before the configure()). Since there was no config, loggers was set to [] and future logs were dropped.

This was an attempted work around for that. Now the initial called to log_line() from a batch won't make all subsequent logs drop. The configure() will set the loggers list correctly. Is there a better way?

**Comment by asottile** [comment]
Let's sit down and monday and see if we can't figure out a way to avoid this.  Silently doing nothing doesn't seem right to me :)

**Comment by ketanyelp** [comment]
Sounds good.

**Comment by jwien001** [comment]
#34
